"""create_initial_entities

Revision ID: ba38670d9729
Revises: 
Create Date: 2026-08-24 15:09:08.058221
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""create_initial_entities

Revision ID: ba38670d9729
Revises: 
Create Date: 2026-08-24 15:09:08.058221
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba38670d9729'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('severity_score', sa.Float(), nullable=True))
    op.add_column('incidents', sa.Column('detected_tags', sa.JSON(), nullable=False))
    op.add_column('incidents', sa.Column('recommended_action', sa.String(length=500), nullable=True))
    op.add_column('incidents', sa.Column('address_text', sa.String(length=500), nullable=True))
    op.add_column('incidents', sa.Column('image_urls', sa.JSON(), nullable=False))
    op.add_column('reports', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('severity_score', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('estimated_volume_m3', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('detected_tags', sa.JSON(), nullable=False))
    op.add_column('reports', sa.Column('recommended_action', sa.String(length=500), nullable=True))
    op.alter_column('reports', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('reports_user_id_fkey'), 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key(op.f('reports_user_id_fkey'), 'reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('reports', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('reports', 'recommended_action')
    op.drop_column('reports', 'detected_tags')
    op.drop_column('reports', 'estimated_volume_m3')
    op.drop_column('reports', 'severity_score')
    op.drop_column('reports', 'confidence')
    op.drop_column('incidents', 'image_urls')
    op.drop_column('incidents', 'address_text')
    op.drop_column('incidents', 'recommended_action')
    op.drop_column('incidents', 'detected_tags')
    op.drop_column('incidents', 'severity_score')
    op.drop_column('incidents', 'confidence')
    # ### end Alembic commands ###
